/****************************************************************************
* @file convert_DEFAULT_2_BSOLocation_helper.java 
* The skeleton for this file is auto-generated from DEXTER. It contains 2
* functions: pre_convert_DEFAULT_2_BSOLocation and 
* post_convert_DEFAULT_2_BSOLocation
*  
* AUTOGENERATED 
****************************************************************************/ 

/* Include files for the data structures and helper functions */
import face.datamodel.DEFAULT;
import face.datamodel.BSOLocation;

/**************************************************************************** 
* pre-convert source structure data fields into destination structure. See
* the auto-generated header file for function documentation.
****************************************************************************/
public class convert_DEFAULT_2_BSOLocation_helper{

public int pre_convert_DEFAULT_2_BSOLocation 
   ( 
   BSOLocation out_ownship_gps_subscriber, 
    DEFAULT in_TRACK_DATA 
   ) 
{ 
    /* insert pre-processing code here */

    /* Success, continue execution */
    return 0; 
} /* end pre_convert_DEFAULT_2_BSOLocation */

/**************************************************************************** 
* post-convert source structure data fields into destination structure. See
* the auto-generated header file for function documentation.
****************************************************************************/ 
public int post_convert_DEFAULT_2_BSOLocation
   ( 
   BSOLocation out_ownship_gps_subscriber, 
    DEFAULT in_TRACK_DATA 
   ) 
{ 
    /* insert post-processing code here */

     /* Success, continue execution */
    return 0; 
} /* end post_convert_DEFAULT_2_BSOLocation */
}