/****************************************************************************
* 
* AUTOGENERATED FILE, DO NOT HAND EDIT THIS FILE! 
* 
* @file convert_Coordinate_Data_2_BSOLocation.java 
* This file is autogenerated from DEXTER. It converts two structures: 
* from Coordinate_Data to BSOLocation. 
*  
* AUTOGENERATED 
****************************************************************************/ 

/* Include files for the data structures and helper functions */ 

/**************************************************************************** 
* Convert source structure data fields into destination structure. 
****************************************************************************/
import face.datamodel.Coordinate_Data;
import face.datamodel.BSOLocation;

public class convert_Coordinate_Data_2_BSOLocation{
    
public int convert_Coordinate_Data_2_BSOLocation( 
   BSOLocation out_ownship_gps_subscriber, 
    Coordinate_Data in_IDS_Coordinate_Data 
   ) 
{ 
    int result=0;
    convert_Coordinate_Data_2_BSOLocation_helper defaultTester = 
    new convert_Coordinate_Data_2_BSOLocation_helper();
    /* Sanity check for NULL pointers */
     if(in_IDS_Coordinate_Data == null || out_ownship_gps_subscriber == null) { 
      return -1; 
    } 

    /* Pre-convert */
    result = defaultTester.pre_convert_Coordinate_Data_2_BSOLocation(out_ownship_gps_subscriber, in_IDS_Coordinate_Data);
    if(0 != result) {
      return result;
    }
     
    /* Map fields */
double tmp_ecef2lla_Out[] = {0,0,0};
ecef2lla conv_ecef2lla = new ecef2lla();
conv_ecef2lla.ecef2lla_conversion(in_IDS_Coordinate_Data.RHX, in_IDS_Coordinate_Data.RHY, in_IDS_Coordinate_Data.DMHX,tmp_ecef2lla_Out);
out_ownship_gps_subscriber.bso_location.longitude = tmp_ecef2lla_Out[0];
out_ownship_gps_subscriber.bso_location.latitude = tmp_ecef2lla_Out[1];
out_ownship_gps_subscriber.bso_location.altitude = tmp_ecef2lla_Out[2];
 

    /* Post-convert */
    result = defaultTester.post_convert_Coordinate_Data_2_BSOLocation(out_ownship_gps_subscriber, in_IDS_Coordinate_Data);

    /* Done */
    return result; 
} /* end convert_Coordinate_Data_2_BSOLocation */
}